// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbTOW5irz2CU1r4SesXufCb8zA3RbPoJM',
    appId: '1:515365752042:web:c3831738e019d9ba1b1b93',
    messagingSenderId: '515365752042',
    projectId: 'inti-warehouse-59fcb',
    authDomain: 'inti-warehouse-59fcb.firebaseapp.com',
    storageBucket: 'inti-warehouse-59fcb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD-eIxaE_zTbPFC5y0u10ke0TTS0IeESo',
    appId: '1:515365752042:android:b3b7870d827b417d1b1b93',
    messagingSenderId: '515365752042',
    projectId: 'inti-warehouse-59fcb',
    storageBucket: 'inti-warehouse-59fcb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ2HkXJDZVqzoyARObb4JYG9BBnQQ79Kw',
    appId: '1:515365752042:ios:b4faa3cb4f3b38761b1b93',
    messagingSenderId: '515365752042',
    projectId: 'inti-warehouse-59fcb',
    storageBucket: 'inti-warehouse-59fcb.appspot.com',
    iosClientId: '515365752042-l5b72836amb32fjd317i79v2981p39os.apps.googleusercontent.com',
    iosBundleId: 'com.example.intiFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ2HkXJDZVqzoyARObb4JYG9BBnQQ79Kw',
    appId: '1:515365752042:ios:b4faa3cb4f3b38761b1b93',
    messagingSenderId: '515365752042',
    projectId: 'inti-warehouse-59fcb',
    storageBucket: 'inti-warehouse-59fcb.appspot.com',
    iosClientId: '515365752042-l5b72836amb32fjd317i79v2981p39os.apps.googleusercontent.com',
    iosBundleId: 'com.example.intiFirebase',
  );
}
